Update check_tlsa
Added smtp (465, 587) port exception

diff --git a/Linux/bash/generic/usr/sbin/check_tlsa b/Linux/bash/generic/usr/sbin/check_tlsa
--- a/Linux/bash/generic/usr/sbin/check_tlsa
+++ b/Linux/bash/generic/usr/sbin/check_tlsa
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
-Version=20100607.01
+Version=20211001.01
 
-# Description:  Script could be referenzed from other scripts to check if a required package is installed.
-# It checks if a package is installed. If not it asks if it should be installed.
+# Description: Script check if the TLSA record for the active certificate matches the DNS published one.
+
+if [ -z "${1}" ] ; then
+  echo "Usage: $0 {port} {domain1.tls} {optional: domain2.tld domain3.tld}"
+fi
 
 set -u
 # -e: exit immidiately when a command fails. If piped check only the last command error code.
@@ -119,8 +122,30 @@ tempfile() {
     mktemp /tmp/${tempprefix}.XXXXXX
 }
 
+
+function color() {
+
+  if [ "${2}" == "green" ]; then
+#   echo -e "\033[40;1;32m"${1}"\033[0m"
+    echo -e "\e[32m"${1}"\e[39m"
+  fi
+
+  if [ "${2}" == "red" ]; then
+#   echo -e "\033[40;1;31m"${1}"\033[0m"
+    echo -e "\e[31m"${1}"\e[39m"
+  fi
+
+  if [ "${2}" == "yellow" ]; then
+#   echo -e "\033[40;1;33m"${1}"\033[0m"
+    echo -e "\e[33m"${1}"\e[39m"
+  fi
+}
+
 main() {
-  for i in "$@" ; do
+  public_dns="127.0.0.1"
+  postmaster=root@localhost
+
+  for i in "${@}" ; do
     if [[ "${i}" == "-V" ]] ; then
        echo  "$(basename "${0}")" "${Version}"
 
@@ -130,111 +155,81 @@ main() {
        echo "Dieses Script wird unter Ausschluss vom Gewährleistung und Garantie bereitgestellt, soweit dies durch Gesetze ermöglicht wird."
        exit 1
     fi
+
     if [[ "${i}" == "-u" ]] ; then
       check_self_update
       exit 1
-    fi    
+    fi
   done
 
+  for i in "${@:2}"; do
+    # Check if A record exists
+    host ${i} | grep "NXDOMAIN" >/dev/null
+    if [ $? -eq 0 ]; then
+      echo "No A record found for ${i}"
+      exit 2
+    else
+      if [ "${1}" -eq "25" ] || [ "${1}" -eq "465" ] || [ "${1}" -eq "587" ]; then
+        domain="$(dig @"${public_dns}" "${i}" MX +short | awk '{print $2}')"
+        if [ -z ${domain} ]; then
+          echo "$(color "No mx found for ${2}!!" red)"
+        else
+          echo "Using mx record: $(color "${domain}" yellow)"
+        fi
+      else
+        domain="${i}"
+      fi
 
-PARAM=""
-TIMEOUT="5"
-RECIPIENT="postmaster@o-o-s.de"
-TEMP=$(tempfile)
+      port="${1}"
 
-trap "rm -f '"${TEMP}"'" exit
+      echo ""
+      echo "DANE record"
+      echo "---------------------------------"
+      temp=$(tempfile)
+      trap "rm -f ${temp}*" 0 1 2 5 15
 
-if [ "$1" = "" ] || [ "$2" = "" ]; then
-        echo "$0 domain.tld port"
-        exit 1
-fi
+      DNSResult="$(dig @"${public_dns}" _"${port}"._tcp."${domain}" IN TLSA +short)"
 
-# identitfy port and set starttls
-if [ $2 = "25" ] || [ $2 = "465" ] || [ $2 = "587" ]; then
-  PARAM="-starttls smtp"
-  PROTOCOL="SMTPs"
-fi
+      echo "DNS TLSA Records:" > "${temp}"
+      echo "------------------" >> "${temp}"
+      while read -r line; do
+        echo "${line}" | awk '{print "_'$port'._tcp.'$domain'. IN TLSA "$1" " $2" "$3" "$4$5}' >> $temp
+        done <<< "${DNSResult}"
+        echo >> "${temp}"
+        echo "Required TLSA Records:" >> "${temp}"
+        echo "---------------------------------------" >> "${temp}"
 
-if [ $2 = "21" ]; then
-  PARAM="-starttls ftp"
-  PROTOCOL="FTPs"
-fi
+        local smtp_parameter=""
+        if [ "${port}" -eq "25" ] || [ "${port}" -eq "465" ] || [ "${port}" -eq "587" ]; then smtp_parameter="-starttls smtp"; fi
+        if [ "${port}" -eq "21" ]; then smtp_parameter="-starttls ftp"; fi
+        nohup openssl s_client -showcerts -verify 5 -connect ${domain}:${port} ${smtp_parameter} < /dev/null | awk '/BEGIN/,/END/{ if(/BEGIN/){a++}; out="'$temp'"a".pem"; print >out}'
 
-if [ $2 = "993" ]; then
-  PROTOCOL="IAMPs"
-fi
+        counter="0"
+        for cert in "${temp}"*.pem;
+        do
+          failed=0
+          if [ "${counter}" -ne "2" ]; then counter=3; fi
+          openssl x509 -noout -subject -in "${cert}"
+          tlsa_record=$(openssl x509 -noout -pubkey -in "${cert}" | openssl rsa -pubin -outform DER 2>/dev/null | openssl sha256 | tr '[:lower:]' '[:upper:]' | awk '{print "_'$port'._tcp.'$domain'. IN TLSA '$counter' 1 1 " $2}';)
+#         tlsa_record=$(openssl x509 -noout -pubkey -in "${cert}" | openssl rsa -pubin -outform DER 2>/dev/null | openssl sha256 | awk '{print "_'$port'._tcp.'$domain'. IN TLSA '$counter' 1 1 " $2}';)
 
-if [ $2 = "995" ]; then
-  PROTOCOL="POP3s"
-fi
+          if grep "${tlsa_record}" "${temp}" > /dev/null
+          then
+            echo "${tlsa_record} $(color "(DNS match)" green)"
+          else
+            echo "${tlsa_record} $(color "(DNS mismatch)" red)"
+            echo "${tlsa_record}" >> $temp
+          failed=1
+          fi
 
-if [ $2 = "443" ]; then
-  PROTOCOL="HTTPs"
-fi
+          counter=2
+          echo
+        done
+        rm "${temp}"* > /dev/null
 
-TLSA=$(dig +nocmd +noall +answer TLSA _$2._tcp.$1. +short | tr '[:upper:]' '[:lower:]')
-
-if [ -z "$TLSA" ]; then
-  echo "no TLSA record"
-  exit
-fi
-
-
-# quit if remote service is not available
-sleep 1 | telnet $1 $2 > "${TEMP}"
-con_status=$(grep -i connected "${TEMP}" | tr '[:upper:]' '[:lower:]')
-if [[ "$con_status" == *connected* ]]; then
-  echo -e Remote Service: $1:$2 \('\E[40;1;32m'"\033\OK\033[0m)"
-else
-  echo -e Remote Service: $1:$2 \('\E[40;1;31m'"\033\DOWN\033[0m)"
-  exit
-fi
-> "${TEMP}"
-
-# _25._tcp_domain.tld TLSA 3 0 1 ADEF...
-#                          ^ ^ ^
-#                          | | - 0: full, 1 SHA256, 2 SHA512
-#                          | - 0: Cert, 1 SPKI
-#                          - 0: Certificate Authority Constraint, 1: PKIX-EE: Service Certificate Constraint,
-#                            2: Trust Anchor Assertion, 3: Domain Issued Certificate
-
-#_25._tcp_domain.tld TLSA 3 0 1 ADEF...
-if [ $(echo $TLSA | awk '{print $2}') = "0" ] && [ $(echo $TLSA | awk '{print $3}') = "1" ]; then
-  cert=$(timeout $TIMEOUT openssl s_client -showcerts -CApath /etc/ssl/certs/ $PARAM -servername $1 -connect $1:$2 < /dev/null | openssl x509 -outform DER | openssl sha256 |grep stdin | awk '{print $2}' | tr '[:upper:]' '[:lower:]')
-fi
-
-#_25._tcp_domain.tld TLSA 3 0 2 ADEF...
-if [ $(echo $TLSA |  awk '{print $2}') = "0" ] && [ $(echo $TLSA | awk '{print $2}') = "2" ]; then
-  cert=$(timeout $TIMEOUT openssl s_client -showcerts -CApath /etc/ssl/certs/ $PARAM -servername $1 -connect $1:$2 < /dev/null | openssl x509 -outform DER | openssl sha512 |grep stdin | awk '{print $2}' | tr '[:upper:]' '[:lower:]')
-fi
-
-
-#_25._tcp_domain.tld TLSA 3 1 1 ADEF...
-if [ $(echo $TLSA |  awk '{print $2}') = "1" ] && [ $(echo $TLSA | awk '{print $2}') = "1" ]; then
-  cert=$(timeout $TIMEOUT openssl s_client $PARAM -servername $1 -connect $1:$2 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | sha256sum | awk '{print $1}' | tr '[:upper:]' '[:lower:]')
-fi
-
-#_25._tcp_domain.tld TLSA 3 1 2 ADEF...
-if [ $(echo $TLSA |  awk '{print $2}') = "1" ] && [ $(echo $TLSA | awk '{print $2}') = "2" ]; then
-  cert=$(timeout $TIMEOUT openssl s_client $PARAM -servername $1 -connect $1:$2 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | sha512sum | awk '{print $1}' | tr '[:upper:]' '[:lower:]')
-fi
-
-# compare both fingerprints and send an email in the case of an mismatch
-if [ $(echo $TLSA | awk '{print $4$5}') = "$cert" ]; then
-  echo -e '[\E[40;1;32m'"\033\ OK\033[0m ] $1"
-else
-  echo -e '[\E[40;1;31m'"\033\ Fail\033[0m ] $1"
-  openssl s_client -servername $1 -connect $1:$2 $PARAM -showcerts < /dev/null | openssl x509 -outform DER > /tmp/$1.cer
-
-  echo "DNS record" >> "${TEMP}"
-  echo "---------------------" >> "${TEMP}"
-  timeout 5 dig +nocmd +noall +answer TLSA _$2._tcp.$1. | tr '[:upper:]' '[:lower:]' >> "${TEMP}"
-  echo "" >> "${TEMP}"
-  echo "Active Zertifikate" >> "${TEMP}"
-  echo "---------------------" >> "${TEMP}"
-  echo "Certificate: $cert" >> "${TEMP}"
-  mutt $RECIPIENT -s "[$1] - $PROTOCOL TLSA error" -a /tmp/$1.cer < "${TEMP}"
-fi  
+        if [ "${failed}" -eq "1" ]; then mutt -s "[$i] - TLSA failed for Port $1" "${postmaster}" < $temp; fi
+    fi
+  done
 }
 
 main "$@"
