Update ddnsupdate

diff --git a/Linux/bash/ddnsupdate/ddnsupdate b/Linux/bash/ddnsupdate/ddnsupdate
--- a/Linux/bash/ddnsupdate/ddnsupdate
+++ b/Linux/bash/ddnsupdate/ddnsupdate
@@ -1,5 +1,5 @@
 #!/bin/bash
-Version=20200311.01
+Version=20200311.02
 
 # Description:
 # Script queried dns ip of given fqdn an compares these with the current public ip of the device.
@@ -16,7 +16,6 @@ Version=20200311.01
 # ${STATE_FILE}:     file to write stat file (ip)
 # ${IP_DETECT_URL}:  URL must send public ip in plaintext
 # ${PRE_UPDATE_CMD}: any command to run before the update command
-# ${LOGFILE}:        file to write log files
 # ${MTIME}:          mtime used for search command
 #
 # Style-Guide: https://google.github.io/styleguide/shell.xml#Case_statement
@@ -36,9 +35,14 @@ DNS_TTL="60"
 STATE_FILE="/tmp/custom_ddns_last_ip"
 IP_DETECT_URL="${5}"
 PRE_UPDATE_CMD=""
-LOGFILE=/tmp/$DNS_RECORD
 UPDATE=0
 MTIME=+10
+
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+
 
 run_self_update() {
   #######################################
@@ -167,6 +171,14 @@ function check_nsupdate {
   fi
 }
 
+
+debug() {
+  if [ "$debug" = "1" ]; then
+    echo
+    echo -e "${YELLOW}\$ $@${NC}"
+  fi
+}
+
 function get_public_ip {
   #######################################
   # Get public ip from a website
@@ -177,7 +189,11 @@ function get_public_ip {
   #######################################
 
   ip=`curl -4 -s -f ${1} | grep -o "[[:digit:].]\+"`
-# ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
+  debug "curl -4 -s -f ${1} | grep -o \"[[:digit:].]\+\""
+
+  echo Current IP: \ ${ip}
+  # remove stat file when older then 10 minutes
+  find /tmp/ -type f -name custom_ddns_last_ip -mmin "${MTIME}" -exec rm {} \;
 }
 
 
@@ -191,15 +207,17 @@ function get_a_record {
   #   None
   #######################################
 
-  DNS_IP=$(host ${1} ${2} | grep "has address" | awk '{print $4}')
+  echo A-Record:\ \ \ \ $1
 
-  echo `date` > /tmp/${DNS_RECORD}
-  echo DNS ${DNS_IP}  >> /tmp/${DNS_RECORD}
-  echo `date`
-  echo DNS IP:\ \ \ \  ${DNS_IP}
-  echo Current IP: ${ip}
-  # remove stat file when older then 10 minutes
-  find /tmp/ -type f -name custom_ddns_last_ip -mmin "${MTIME}" -exec rm {} \;
+  debug "host ${1} ${2} | grep \"has address\" | awk '{print $4}'"
+
+  if ! DNS_IP=$(host ${1} ${2} | grep "has address" | awk '{print $4}') >/dev/null 2>&1 ; then
+    echo DNS IP:\ \ \ \ \ \ Not present. Forcing update!
+    logger -t "ddnsupdate" "A record $1 not found. Forcing update!"
+    UPDATE=1
+  else
+      echo DNS IP:\ \ \ \ \ \ ${DNS_IP}
+  fi
 }
 
 function dns_update_check {
@@ -211,35 +229,34 @@ function dns_update_check {
   #   None
   #######################################
 
+  if [ "${DNS_IP}" != "{ip}" ]; then
+    UPDATE=1
+  fi
+
   if [ -z "${ip}" ]; then
-    echo "Can't get the public IP, no Internet connection?" >> /tmp/${DNS_RECORD}
     echo "Can't get the public IP, no Internet connection?"
     logger -t "ddnsupdate" "Can't get the public IP, no Internet connection"
     exit 1
   fi
 
   if [ ! -f ${STATE_FILE} ]; then
-    echo State file: does not exist, check dns  >> /tmp/${DNS_RECORD}
-    echo State file: does not exist, check dns
+    echo State file: \ does not exist, check dns
     logger -t "ddnsupdate" "state file does not exist, check dns."
     UPDATE=1
   else
+    debug "600 - (stat -c %Z ${STATE_FILE}) - (date +%s)"
     STAT_FILE_AGE=`stat -c %Z ${STATE_FILE}`; NOW=`date +%s`; (( DIFF = (NOW - STAT_FILE_AGE) )); STAT_FILE_AGE="$[600-$DIFF]";
-    echo State file: to early for doublecheck  >> /tmp/${DNS_RECORD}
-    echo "State file: to early for doublecheck (${STAT_FILE_AGE} sec. remaining)"
-    logger -t "ddnsupdate" "to early for doublecheck (${STAT_FILE_AGE} sec. remaining)"
-    exit 1
+    echo "State file:  To early for doublecheck (${STAT_FILE_AGE} sec. remaining)".
+    logger -t "ddnsupdate" "To early for doublecheck (${STAT_FILE_AGE} sec. remaining)"
+#    exit 1
   fi
 
   if [ "${UPDATE}" == "1" ]; then
-    DNS_IP=$(host ${DNS_RECORD} $DNS_SERVER | grep "has address" | awk '{print $4}')
+#    DNS_IP=$(host ${DNS_RECORD} $DNS_SERVER | grep "has address" | awk '{print $4}')
 
-    echo DNS: ${DNS_IP} >> /tmp/${DNS_RECORD}
-    echo current: ${ip} >> /tmp/${DNS_RECORD}
     if [ "${DNS_IP}" != "${ip}" ]; then
-      echo DDNS-Status: need update >> /tmp/${DNS_RECORD}
-      echo "DDNS-Status: need update (DNS=${DNS_IP}, IP=${ip})"
-      logger -t "ddnsupdate" "need update. (DNS=${DNS_IP}, IP=${ip})"
+      echo "DDNS-Status: Need update (DNS=${DNS_IP}, IP=${ip})"
+      logger -t "ddnsupdate" "Need update. (DNS=${DNS_IP}, IP=${ip})"
       #some preupdate commands?
       ${PRE_UPDATE_CMD}
       #creating /usr/bin/nsupdate commands
@@ -249,6 +266,7 @@ function dns_update_check {
          commands="${commands}\nupdate delete ${i} A\nupdate add ${i} ${DNS_TTL} A ${ip}\nupdate delete ${i} txt\nupdate add ${i} $DNS_TTL TXT \"$(date +%d.%m.%Y,\ %H:%M:%S\ %Z\ \(%:::z\))\"\n"
       done
 
+     debug "${commands} | /usr/bin/nsupdate -k ${DNS_KEY_FILE}"
       commands="${commands}\nsend\n"
       #running dns update
       echo -e "${commands}" | /usr/bin/nsupdate -k ${DNS_KEY_FILE}
@@ -256,26 +274,23 @@ function dns_update_check {
       nsupdate_status=${?}
      #checking nsupdate exit status
       if [ ${nsupdate_status} -ne 0 ]; then
-        echo "DNS update failed! Wrong configuration?" >> /tmp/${DNS_RECORD}
         echo "DNS update failed! Wrong configuration?"
         logger -t "ddnsupdate" "DNS update failed! Wrong configuration?"
 #        exit 1
       else
         logger -t "ddnsupdate" "${DNS_RECORD} updated to ${ip}."
-        echo ${DNS_RECORD} updated to ${ip} >> /tmp/${DNS_RECORD}
-        echo "${DNS_RECORD} updated to ${ip}"
+        echo Action:\ \ \ \ \ \ Updated to ${ip}
         #writing our ip to state file
         echo "${ip}">$STATE_FILE
       fi
     else
-      echo DDNS-Status: update not neccessary >> /tmp/${DNS_RECORD}
       echo "DDNS-Status: update not neccessary (DNS=${DNS_IP}, IP=${ip})"
       logger -t "ddnsupdate" "update not neccessary. (DNS=${DNS_IP}, IP=${ip})"
       echo "${ip}">${STATE_FILE}
 #      exit 1
     fi
   else
-    echo exit
+   exit
   fi
 }
 
@@ -284,6 +299,9 @@ main() {
     if [[ "${i}" == "-u" ]] ; then
       check_self_update
       exit 1
+    fi
+    if [[ "${i}" == "-v" ]] ; then
+      debug=1
     fi
   done
 
